### ISSUE TITLE
what is this plugin for?

### ISSUE THREAD

**Issue by exomarty** [BenLubar/nodebb-plugin-htmlcleaner#1]
readme was so long :dancer:

**Comment by BenLubar** [comment]
It cleans HTML using [this config](https://github.com/BenLubar/nodebb-plugin-htmlcleaner/blob/master/cleaner/config.go). We use it on The Daily WTF so we can allow HTML without having XSS vulnerabilities.

**Comment by exomarty** [comment]
so you allow html on composer then install this?

thanks for the info :)
